name: Test Rust Project

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: "true"
          toolchain: stable

      - name: Run tests
        id: cargo_test
        run: |
          cargo test --test skeptic -- --test-threads=1

      - name: Test Results
        if: always()
        run: |
          if [ "${{ steps.cargo_test.outcome }}" == "success" ]; then
            echo "✅ All tests passed!"
          else
            echo "❌ Some tests failed. Check the logs above for details."
            exit 1
          fi
  check-workspace:
    # this job incrementally replaces the skeptic tests above as we convert examples to be written
    # as workspace crates rather than inline in the mdbook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: cargo check
        id: cargo_check
        run: cargo check --workspace
      - name: Check Results
        if: always()
        run: |
          if [ "${{ steps.cargo_check.outcome }}" == "success" ]; then
            echo "✅ Workspace check passed!"
          else
            echo "❌ Workspace check failed. Check the logs above for details."
            exit 1
          fi
